version: "3.9"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: kelasi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - infra_db_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  infra_db_data: