version: "3.9"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: kelasi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: db
    depends_on:
      - db
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    ports:
      - "3000:3000"

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - frontend
      - backend
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

volumes:
  db_data: